defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: chimpance99
  socket: /tmp/mysql.sock

development:
  database: renato_development
  <<: *defaults

test: &test
  database: renato_test
  <<: *defaults

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: 174.121.79.98
  database: renato_production
  pool: 5
  username: renato_db
  password: chimpance99

cucumber:
  <<: *test
